/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package forest.banyan;

import com.google.inject.Guice;
import com.google.inject.Injector;
import forest.banyan.resources.TestResource;
import io.dropwizard.core.Application;
import io.dropwizard.core.setup.Environment;

public class BanyanApplication extends Application<BanyanConfiguration> {

  private static final String NAME = "Banyan";

  public static void main(final String[] args) throws Exception {
    new BanyanApplication().run(args);
  }

  @Override
  public String getName() {
    return NAME;
  }

  @Override
  public void run(final BanyanConfiguration configuration, final Environment environment) {
    final Injector injector = Guice.createInjector();
    final BanyanHealthCheck healthCheck = new BanyanHealthCheck(getName());
    environment.healthChecks().register("template", healthCheck);
    environment.jersey().register(new TestResource());
  }
}
