/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package forest.banyan.utils;

public class MessageUtils {
  public static String getMessage() {
    return "Hello      World!";
  }
}
